## **SVM for Classification**

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


In [3]:
df = pd.read_csv("/content/drive/My Drive/Colab Notebooks/movie_analysis/Movie_classification.csv", header=0)

In [4]:
pwd

'/content'

In [5]:
df.head()

Marketing expense  Production expense  ...  Collection  Start_Tech_Oscar
0            20.1264               59.62  ...       48000                 1
1            20.5462               69.14  ...       43200                 0
2            20.5458               69.14  ...       69400                 1
3            20.6474               59.36  ...       66800                 1
4            21.3810               59.36  ...       72400                 1

[5 rows x 19 columns]

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Marketing expense    506 non-null    float64
 1   Production expense   506 non-null    float64
 2   Multiplex coverage   506 non-null    float64
 3   Budget               506 non-null    float64
 4   Movie_length         506 non-null    float64
 5   Lead_ Actor_Rating   506 non-null    float64
 6   Lead_Actress_rating  506 non-null    float64
 7   Director_rating      506 non-null    float64
 8   Producer_rating      506 non-null    float64
 9   Critic_rating        506 non-null    float64
 10  Trailer_views        506 non-null    int64  
 11  3D_available         506 non-null    object 
 12  Time_taken           494 non-null    float64
 13  Twitter_hastags      506 non-null    float64
 14  Genre                506 non-null    object 
 15  Avg_age_actors       506 non-null    int

In [7]:
df.describe()

Marketing expense  Production expense  ...     Collection  Start_Tech_Oscar
count         506.000000          506.000000  ...     506.000000        506.000000
mean           92.270471           77.273557  ...   45057.707510          0.545455
std           172.030902           13.720706  ...   18364.351764          0.498422
min            20.126400           55.920000  ...   10000.000000          0.000000
25%            21.640900           65.380000  ...   34050.000000          0.000000
50%            25.130200           74.380000  ...   42400.000000          1.000000
75%            93.541650           91.200000  ...   50000.000000          1.000000
max          1799.524000          110.480000  ...  100000.000000          1.000000

[8 rows x 17 columns]

### Missing Value Imputation

In [8]:
df['Time_taken'].mean()

157.39149797570855

In [9]:
df['Time_taken'].fillna(value = df['Time_taken'].mean(), inplace = True)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Marketing expense    506 non-null    float64
 1   Production expense   506 non-null    float64
 2   Multiplex coverage   506 non-null    float64
 3   Budget               506 non-null    float64
 4   Movie_length         506 non-null    float64
 5   Lead_ Actor_Rating   506 non-null    float64
 6   Lead_Actress_rating  506 non-null    float64
 7   Director_rating      506 non-null    float64
 8   Producer_rating      506 non-null    float64
 9   Critic_rating        506 non-null    float64
 10  Trailer_views        506 non-null    int64  
 11  3D_available         506 non-null    object 
 12  Time_taken           506 non-null    float64
 13  Twitter_hastags      506 non-null    float64
 14  Genre                506 non-null    object 
 15  Avg_age_actors       506 non-null    int

### Dummy Variable Creation

In [11]:
df.head()

Marketing expense  Production expense  ...  Collection  Start_Tech_Oscar
0            20.1264               59.62  ...       48000                 1
1            20.5462               69.14  ...       43200                 0
2            20.5458               69.14  ...       69400                 1
3            20.6474               59.36  ...       66800                 1
4            21.3810               59.36  ...       72400                 1

[5 rows x 19 columns]

In [12]:
df = pd.get_dummies(df,columns = ["3D_available","Genre"],drop_first = True)

In [13]:
df.head()

Marketing expense  Production expense  ...  Genre_Drama  Genre_Thriller
0            20.1264               59.62  ...            0               1
1            20.5462               69.14  ...            1               0
2            20.5458               69.14  ...            0               0
3            20.6474               59.36  ...            1               0
4            21.3810               59.36  ...            1               0

[5 rows x 21 columns]

### X-y split

In [14]:
X = df.loc[:,df.columns!="Start_Tech_Oscar"]
type(X)

pandas.core.frame.DataFrame

In [15]:
X.head()

Marketing expense  Production expense  ...  Genre_Drama  Genre_Thriller
0            20.1264               59.62  ...            0               1
1            20.5462               69.14  ...            1               0
2            20.5458               69.14  ...            0               0
3            20.6474               59.36  ...            1               0
4            21.3810               59.36  ...            1               0

[5 rows x 20 columns]

In [16]:
X.shape

(506, 20)

In [17]:
y = df["Start_Tech_Oscar"]
type(y)

pandas.core.series.Series

In [18]:
y.head()

0    1
1    0
2    1
3    1
4    1
Name: Start_Tech_Oscar, dtype: int64

In [19]:
y.shape

(506,)

### Test-Train Split

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2,random_state=0)

In [22]:
X_train.head()

Marketing expense  Production expense  ...  Genre_Drama  Genre_Thriller
220            27.1618               67.40  ...            0               1
71             23.1752               76.62  ...            0               0
240            22.2658               64.86  ...            0               0
6              21.7658               70.74  ...            0               1
417           538.8120               91.20  ...            0               0

[5 rows x 20 columns]

In [23]:
X_train.shape

(404, 20)

In [24]:
X_test.shape

(102, 20)

### Standardizing Data

In [25]:
from sklearn.preprocessing import StandardScaler

In [26]:
sc = StandardScaler().fit(X_train)

In [27]:
X_train_std = sc.transform(X_train)

In [28]:
X_test_std = sc.transform(X_test)

In [29]:
X_test_std

array([[-0.40835869, -1.12872913,  0.83336883, ...,  1.50268577,
        -0.48525664, -0.75225758],
       [ 0.71925111,  0.9988844 , -0.65283979, ...,  1.50268577,
        -0.48525664, -0.75225758],
       [-0.40257488,  0.39610829,  0.05115377, ...,  1.50268577,
        -0.48525664, -0.75225758],
       ...,
       [-0.3982601 , -0.85812418,  0.89420778, ..., -0.66547513,
        -0.48525664,  1.3293319 ],
       [-0.39934279, -0.07637654,  0.58132175, ...,  1.50268577,
        -0.48525664, -0.75225758],
       [-0.40088071, -0.36702631,  0.31189212, ..., -0.66547513,
        -0.48525664, -0.75225758]])

### Training SVM

https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html

In [30]:
from sklearn import svm

In [31]:
clf_svm_l = svm.SVC(kernel='linear', C=100)
clf_svm_l.fit(X_train_std, y_train)

SVC(C=100, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

### Predict values using trained model

In [32]:
y_train_pred = clf_svm_l.predict(X_train_std)
y_test_pred = clf_svm_l.predict(X_test_std)

In [33]:
y_test_pred

array([1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0])

### Model Performance

In [34]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [35]:
confusion_matrix(y_test, y_test_pred)

array([[25, 19],
       [25, 33]])

In [36]:
accuracy_score(y_test, y_test_pred)

0.5686274509803921

In [37]:
clf_svm_l.n_support_

array([144, 146], dtype=int32)

### Grid Search

In [38]:
from sklearn.model_selection import GridSearchCV 

In [39]:
params = {'C':(0.001,0.005,0.01,0.05, 0.1, 0.5, 1, 5, 10, 50,100,500,1000)} 

In [40]:
clf_svm_l = svm.SVC(kernel='linear')

In [41]:
svm_grid_lin = GridSearchCV(clf_svm_l, params, n_jobs=-1,
                            cv=10, verbose=1, scoring='accuracy') 

In [42]:
svm_grid_lin.fit(X_train_std, y_train)

Fitting 10 folds for each of 13 candidates, totalling 130 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done 120 tasks      | elapsed:   37.2s
[Parallel(n_jobs=-1)]: Done 130 out of 130 | elapsed:  1.8min finished


GridSearchCV(cv=10, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='linear', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=-1,
             param_grid={'C': (0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1, 5, 10, 50,
                               100, 500, 1000)},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='accuracy', verbose=1)

In [43]:
svm_grid_lin.best_params_ 

{'C': 0.1}

In [44]:
linsvm_clf = svm_grid_lin.best_estimator_

In [45]:
accuracy_score(y_test, linsvm_clf.predict(X_test_std))

0.5980392156862745

### Polynomial

In [46]:
clf_svm_p3 = svm.SVC(kernel='poly', degree=2, C=0.1)
clf_svm_p3.fit(X_train_std, y_train)

SVC(C=0.1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=2, gamma='scale', kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [47]:
y_train_pred = clf_svm_p3.predict(X_train_std)
y_test_pred = clf_svm_p3.predict(X_test_std)

In [48]:
accuracy_score(y_test, y_test_pred)

0.5588235294117647

In [49]:
clf_svm_p3.n_support_

array([185, 194], dtype=int32)

### Radial

In [50]:
clf_svm_r = svm.SVC(kernel='rbf', gamma=0.5, C=10)
clf_svm_r.fit(X_train_std, y_train)

SVC(C=10, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.5, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [51]:
y_train_pred = clf_svm_r.predict(X_train_std)
y_test_pred = clf_svm_r.predict(X_test_std)

In [52]:
accuracy_score(y_test, y_test_pred)

0.6176470588235294

In [53]:
clf_svm_r.n_support_

array([186, 218], dtype=int32)

### Radial Grid

In [54]:
params = {'C':(0.01,0.05, 0.1, 0.5, 1, 5, 10, 50), 
          'gamma':(0.001, 0.01, 0.1, 0.5, 1)} 

In [55]:
clf_svm_r = svm.SVC(kernel='rbf')

In [56]:
svm_grid_rad = GridSearchCV(clf_svm_r, params, n_jobs=-1,
                            cv=3, verbose=1, scoring='accuracy') 

In [57]:
svm_grid_rad.fit(X_train_std, y_train)

Fitting 3 folds for each of 40 candidates, totalling 120 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done 120 out of 120 | elapsed:    1.8s finished


GridSearchCV(cv=3, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=-1,
             param_grid={'C': (0.01, 0.05, 0.1, 0.5, 1, 5, 10, 50),
                         'gamma': (0.001, 0.01, 0.1, 0.5, 1)},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='accuracy', verbose=1)

In [58]:
svm_grid_rad.best_params_ 

{'C': 50, 'gamma': 0.001}

In [59]:
radsvm_clf = svm_grid_rad.best_estimator_

In [60]:
accuracy_score(y_test, radsvm_clf.predict(X_test_std))

0.6176470588235294